[from-internal]
exten => _4.,1,Record(${EXTEN:1}:gsm)
exten => _4.,n,wait(1)
exten => _4.,n,Playback(${EXTEN:1})
exten => _4.,n,Hangup()
;Call Parking
include => parkedcalls

exten=>5000,1,Gosub(stdexten,s,1(PJSIP/john,${EXTEN}))
exten=>5001,1,Gosub(stdexten,s,1(PJSIP/uche,${EXTEN}))
exten=>5002,1,Gosub(stdexten,s,1(PJSIP/mark,${EXTEN}))
exten=>5,1,Confbridge(main)
exten=>8,1,voicemailmain()
; Music on Hold test
exten => 8100,1,Answer()
exten => 8100,n,MusicOnHold(default,30)
exten =>_9.,1,dial(SIP/siptrunk/${EXTEN:1},20)

[from-siptrunk]
include=>assiptrunk

[assiptrunk]
[exten=>9999,1,answer()
exten=>9999,n,background(menu2)
exten=>9999,n,WaitExten(10)
exten=>9999,n,Dial(${OPERATOR})
exten=>1,1,dial(SIP/john)
exten=>2,1,dial(SIP/uche)
exten=>3,1,dial(SIP/mark)
exten=>5000,1,Dial(SIP/john)
exten=>5001,1,Dial(SIP/uche)
exten=>5002,1,Dial(SIP/mark)


[stdexten]
exten=>s,1,Dial(${ARG1},20,tT)
exten=>s,n,Goto(${DIALSTATUS})
exten=>s,n,hangup()
exten=>s,n(BUSY),voicemail(${ARG2},b)
exten=>s,n,hangup()
exten=>s,n(NOANSWER),voicemail(${ARG2},u)
exten=>s,n,hangup()
exten=>s,n(CANCEL),hangup
exten=>s,n(CHANUNAVAIL),hangup
exten=>s,n(CONGESTION),hangup

