[general]
bindport = 5060
bindaddr = 0.0.0.0
allowguest = no
disallow = all
allow = ulaw

[john]
type=friend
secret=mark090#
host=dynamic
context=from-internal

[uche]
type=friend
secret=mark090#
host=dynamic
context=from-internal

[mark]
type=friend
secret=mark090#
host=dynamic
context=from-internal
